Feature/b 5
oleggd/java-training-movieland pull request #11
Opened 2018-12-03 18:53 UTC by oleggd

- Movie getAll with sort order parameters
- Test for query builder
- Need to fix original MovieController tests

2018-12-03 21:45 UTC, Rooman commented on src/main/java/com/movieland/dao/jdbc/RequestParameters.java
> +    private String sortDirection;
используем enum тут

2018-12-03 21:46 UTC, Rooman commented on src/main/java/com/movieland/controller/MovieController.java
> +                                       @RequestParam(value = "rating", required = false) String ratingOrder,
конфигурируем спринг так что бы сюда приходил сразу enum вместо строки

2018-12-03 21:46 UTC, Rooman requested changes

2018-12-03 21:46 UTC, Rooman commented on src/main/java/com/movieland/dao/jdbc/RequestParameters.java
> +    private String sortColumn;
переименовываем из column в field

2018-12-04 11:39 UTC, oleggd commented on src/main/java/com/movieland/dao/jdbc/RequestParameters.java
> +    private String sortDirection;
Fixed

2018-12-04 11:39 UTC, oleggd commented on src/main/java/com/movieland/controller/MovieController.java
> +                                       @RequestParam(value = "rating", required = false) String ratingOrder,
Fixed

2018-12-04 11:40 UTC, oleggd commented on src/main/java/com/movieland/dao/jdbc/RequestParameters.java
> +    private String sortColumn;
Fixed

2018-12-07 08:43 UTC, closed without merging